### ISSUE TITLE
Playback error

### ISSUE THREAD

**Issue by weber8thomas** [tsaridas/stremio-docker#20]
Hi,

Thanks a lot for your work, I was looking into something similar recently!

I tried to setup stremio using your guidelines but I'm facing a playback error when starting a stream.

You'll find my config and logs below:

```
services:
  stremio:
    image: tsaridas/stremio-docker:latest
    restart: unless-stopped
    environment:
      NO_CORS: 1
      IPADDRESS: "192.168.0.12" # Setup your ip address here
    ports:
      - "8080:8080"
      - "11470:11470" # Just one of the two should be enough
      - "12470:12470"
    volumes:
      - "./stremio/:/root/.stremio-server" # set the first part to your local folder. Its not required though
```
      
    

<img width="692" alt="image" src="https://github.com/tsaridas/stremio-docker/assets/32496011/46d3d834-f378-4420-a62a-9b0ada4ec2e6">

```
stremio-1  | Node.js v18.20.0
stremio-1  | hls executables located ->  {
stremio-1  |   ffmpeg: '/usr/bin/ffmpeg',
stremio-1  |   ffsplit: null,
stremio-1  |   ffprobe: '/usr/bin/ffprobe'
stremio-1  | }
stremio-1  | Using app path -> /root/.stremio-server
stremio-1  | Enabling casting...
stremio-1  | (node:7) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
stremio-1  | (Use `node --trace-deprecation ...` to show where the warning was created)
stremio-1  | EngineFS server started at http://127.0.0.1:11470
stremio-1  | EngineFS HTTPS endpoint at https://local.strem.io:12470
stremio-1  |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
stremio-1  |                                  Dload  Upload   Total   Spent    Left  Speed
stremio-1  | -> GET /get-https??authKey=&ipAddress=192.168.0.12
100    92  100    92    0     0    283      0 --:--:-- --:--:-- --:--:--   283
stremio-1  | {"ipAddress":"192.168.0.12","domain":"192-168-0-12.519b6502d940.stremio.rocks","port":12470}Starting up http-server, serving build/ through https
stremio-1  |
stremio-1  | http-server version: 14.1.1
stremio-1  |
stremio-1  | http-server settings:
stremio-1  | CORS: disabled
stremio-1  | Cache: 3600 seconds
stremio-1  | Connection Timeout: 120 seconds
stremio-1  | Directory Listings: not visible
stremio-1  | AutoIndex: visible
stremio-1  | Serve GZIP Files: false
stremio-1  | Serve Brotli Files: false
stremio-1  | Default File Extension: none
stremio-1  |
stremio-1  | Available on:
stremio-1  |   https://127.0.0.1:8080
stremio-1  |   https://172.30.0.2:8080
stremio-1  | Hit CTRL-C to stop the server
stremio-1  |
stremio-1  | -> GET /settings
```

<img width="986" alt="image" src="https://github.com/tsaridas/stremio-docker/assets/32496011/a2639207-cd9b-4551-9a97-ace616dfd442">

```
stremio-1  | -> GET /casting
stremio-1  | -> GET /opensubHash?videoUrl=https%3A%2F%2F192-168-0-12.519b6502d940.stremio.rocks%3A12470%2Fe797fe3be07c17a60fae0b8e2f278d0389aa2391%2F0
stremio-1  | -> HEAD /e797fe3be07c17a60fae0b8e2f278d0389aa2391/0
stremio-1  | Engine created for e797fe3be07c17a60fae0b8e2f278d0389aa2391
stremio-1  | -> GET /e797fe3be07c17a60fae0b8e2f278d0389aa2391/0 bytes=0-
stremio-1  | /srv/stremio-server/server.js:33726
stremio-1  |                 return parseFloat(value.replace(/([\d.]+)(\w?)/, (function(_, val, unit) {
stremio-1  |                                         ^
stremio-1  |
stremio-1  | TypeError: Cannot read properties of undefined (reading 'replace')
stremio-1  |     at parseValue (/srv/stremio-server/server.js:33726:41)
stremio-1  |     at /srv/stremio-server/server.js:33741:31
stremio-1  |     at ChildProcess.exithandler (node:child_process:414:7)
stremio-1  |     at ChildProcess.emit (node:events:517:28)
stremio-1  |     at ChildProcess.emit (node:domain:489:12)
stremio-1  |     at maybeClose (node:internal/child_process:1098:16)
stremio-1  |     at Socket.<anonymous> (node:internal/child_process:450:11)
stremio-1  |     at Socket.emit (node:events:517:28)
stremio-1  |     at Socket.emit (node:domain:489:12)
stremio-1  |     at Pipe.<anonymous> (node:net:350:12)
stremio-1  |
stremio-1  | Node.js v18.20.0
```

Thanks a lot in advance!
