### ISSUE TITLE
failed to start stream server

### ISSUE THREAD

**Issue by rain2307** [tsaridas/stremio-docker#51]
Hi, I cannot start the server.
![屏幕截图_20241101_203348-1](https://github.com/user-attachments/assets/cdb82d4a-0e27-4ca8-a8f7-fed7d4cf54b0)

Docker Setting:
Docker version 20.10.24+dfsg1, build 297e128

```dockerfile
  stremio-docker:
    container_name: stremio-docker
    volumes:
      - /home/ddd/app/stremio:/root/.stremio-server
    ports:
      - 7000:8080/tcp
      - 13470:12470/tcp
    restart: unless-stopped
    image: tsaridas/stremio-docker:latest
```
System:
```
    ,g$$$$$$$$$$$$$$$P.       ------------------ 
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux 12 (bookworm) x86_64 
 ,$$P'              `$$$.     Kernel: 6.1.0-26-amd64 
`d$$'     ,$P"'   .    $$$    Packages: 2017 (dpkg) 
 $$P      d$'     ,    $$P    Shell: bash 5.2.15 
 $$:      $$.   -    ,d$$'    Terminal: /dev/pts/0 
 $$;      Y$b._   _,d$P'      CPU: Intel Pentium 4415U (4) @ 2.300GHz 
 Y$$.    `.`"Y$$$$P"'         GPU: Intel HD Graphics 610 
 `$$b      "-.__              Memory: 2879MiB / 15915MiB 
```

When trying to attach to docker:
```
service "stremio-docker" is not running
```

Thank you.

**Comment by tsaridas** [comment]
cab you post the logs ?

**Comment by tsaridas** [comment]
it shouldn't try to get https certificate. are you sure compose file looks like that ?
```
  stremio-docker:
    container_name: stremio-docker
    volumes:
      - /home/ddd/app/stremio:/root/.stremio-server
    ports:
      - 7000:8080/tcp
      - 13470:12470/tcp
    restart: unless-stopped
    image: tsaridas/stremio-docker:latest
 ```
