### ISSUE TITLE
Transcoding not working on Sandybridge IGPU

### ISSUE THREAD

**Issue by ameeno** [tsaridas/stremio-docker#84]
I have this in docker, and my jellyfin instance can transcode fine with similar settings, but this one doesn't do hardware accelaration, so display is laggy even tho downloads are fast!!

```
stremio-svr:
      image: tsaridas/stremio-docker:latest
      # render group is 105 on docker host.
      group_add:
        - "44"
        - "105" 
      devices:
        - "/dev/dri/card1:/dev/dri/card1"
        - "/dev/dri/renderD128:/dev/dri/renderD128"
      environment:
        - MESA_LOADER_DRIVER_OVERRIDE=crocus
        - LIBVA_DRIVER_NAME=i965
        - NO_CORS=1
        - CASTING_DISABLED=1
```

same settings work on my jellyfin but not this 1.

please help, my igpu is intel hd2000
